/ App.vue

<template>
  <div id="app">
    <center><img src=./assets/bloque64_iso_400.png></center>
    <nav>
        <ul class="topnav">
          <!-- <li><router-link to='/'><img src=./assets/bloque64_logo_35x35_no_circle.png></router-link></li> -->
          <li><router-link to='/'><img src=./assets/bloque64_logo_35x35_no_circle.png></router-link></li>
          <li><a><router-link to='/politica'>Política</router-link></a></li>
           <li><a><router-link to='/economia'>Economia</router-link></a></li>
           <li><a><router-link to='/sociedad'>Sociedad</router-link></a></li>
           <li><a><router-link to='/musica'>Música</router-link></a></li>
           <li><a><router-link to='/deportes'>Deportes</router-link></a></li>
           <li><a><router-link to='/tecnologia'>Tecnología</router-link></a></li>
          <li><a><router-link to='/ciencia'>Ciencia</router-link></a></li>
          <li><a><router-link to='/salud'>Salud</router-link></a></li>
          <li><a><router-link to='/opinion'>Opinión</router-link></a></li>
          <li><a><router-link to='/blockchain'>Blockchain</router-link></a></li>
            
          <li class="right"><a><router-link to='/register'>Registro</router-link></a></li>
          <li class="right"><a> <router-link to='/login'>Login</router-link></a></li>
        </ul>
    </nav>
    <router-view />

    	<footer class="footer-basic-centered">

			<p class="footer-company-motto">El portal de noticias descentratralizado en castellano</p>

			<p class="footer-links">
				<a href="#">Portada</a>
				·
				<a href="#">Blog</a>
				·
				<a href="#">Sobre Nosotros</a>
				·
				<a href="#">FAQ</a>
				·
				<a href="#">Contacto</a>
			</p>

			<p class="footer-company-name">Bloque64 &copy; 2019</p>

		</footer>
 
  </div>


</template>

<script>
export default {
}
</script>

<style>

/* #### Generated By: http://www.cufonfonts.com #### */

@font-face {
font-family: 'American Typewriter';
font-style: normal;
font-weight: normal;
src: local('American Typewriter'), url('./assets/fonts/ufonts.com_american-typewriter.woff') format('woff');
}


@font-face {
font-family: 'American Typewriter Condensed';
font-style: normal;
font-weight: normal;
src: local('American Typewriter Condensed'), url('./assets/fonts/ufonts.com_american-typewriter-condensed.woff') format('woff');
}


@font-face {
font-family: 'American Typewriter Condensed Light';
font-style: normal;
font-weight: normal;
src: local('American Typewriter Condensed Light'), url('./assets/fonts/ufonts.com_american-typewriter-condensed-light.woff') format('woff');
}


@font-face {
font-family: 'American Typewriter Light';
font-style: normal;
font-weight: normal;
src: local('American Typewriter Light'), url('./assets/fonts/ufonts.com_american-typewriter-light.woff') format('woff');
}


@font-face {
font-family: 'American Typewriter Bold';
font-style: normal;
font-weight: normal;
src: local('American Typewriter Bold'), url('./assets/fonts/ufonts.com_american-typewriter-bold.woff') format('woff');
}


@font-face {
font-family: 'American Typewriter Condensed Bold';
font-style: normal;
font-weight: normal;
src: local('American Typewriter Condensed Bold'), url('./assets/fonts/ufonts.com_american-typewriter-condensed-bold.woff') format('woff');
}

body {margin: 1;}

ul.topnav li a:hover:not(.active) {background-color: #D2D2D2;}

ul.topnav li a.active {background-color: #D2D2D2;}

ul.topnav li.right {float: right;}

@media screen and (max-width: 600px) {
  ul.topnav li.right, 
  ul.topnav li {float: none;}
}

ul.topnav {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #D2D2D2;
  font: normal 14px American Typewriter;
}

ul.topnav li {float: left;}

ul.topnav li a {
  display: block;
  color: black;
  text-align: center;
  vertical-align: middle;
  padding: 7px 7px;
  text-decoration: none;
}

ul.topnav li a:hover:not(.active) {background-color: #073C51;}

.footer-basic-centered{
	background-color: #073C51;
	box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.12);
	box-sizing: border-box;
	width: 100%;
	text-align: center;
	font: normal 13px American Typewriter;

	padding: 45px;
	margin-top: 40px;
}

.footer-basic-centered .footer-company-motto{
	color:  #8d9093;
	font-size: 18px;
	margin: 0;
}

.footer-basic-centered .footer-company-name{
	color:  #8f9296;
	font-size: 14px;
	margin: 0;
}

.footer-basic-centered .footer-links{
	list-style: none;
	font-weight: bold;
	color:  #ffffff;
	padding: 35px 0 23px;
	margin: 0;
}

.footer-basic-centered .footer-links a{
	display:inline-block;
	text-decoration: none;
	color: inherit;
}

/* If you don't want the footer to be responsive, remove these media queries */

@media (max-width: 600px) {

	.footer-basic-centered{
		padding: 35px;
	}

	.footer-basic-centered .footer-company-motto{
		font-size: 18px;
	}

	.footer-basic-centered .footer-company-name{
		font-size: 12px;
	}

	.footer-basic-centered .footer-links{
		font-size: 14px;
		padding: 25px 0 20px;
	}

	.footer-basic-centered .footer-links a{
		line-height: 1.8;
	}
}


</style> 
