/ App.vue

<template>
  
  <div id="app">
		

    <top-bar/>
    <center><img src=./assets/bloque64_iso_400.png></center>
    <navigation-bar/>
    <router-view/>ff
    <footer-panel/>
 
  </div>


</template>

<script>

import NavigationBar from '@/components/NavigationBar.vue'
import FooterPanel from '@/components/FooterPanel.vue'
import TopBar from '@/components/TopBar.vue'

export default {

	name: 'app',
	components: {
		'navigation-bar': NavigationBar,
    'footer-panel': FooterPanel,
    'top-bar': TopBar,
	}
}
</script>

<style>

/* #### Generated By: http://www.cufonfonts.com #### */

@font-face {
font-family: 'American Typewriter';
font-style: normal;
font-weight: normal;
src: local('American Typewriter'), url('./assets/fonts/ufonts.com_american-typewriter.woff') format('woff');
}


@font-face {
font-family: 'American Typewriter Condensed';
font-style: normal;
font-weight: normal;
src: local('American Typewriter Condensed'), url('./assets/fonts/ufonts.com_american-typewriter-condensed.woff') format('woff');
}


@font-face {
font-family: 'American Typewriter Condensed Light';
font-style: normal;
font-weight: normal;
src: local('American Typewriter Condensed Light'), url('./assets/fonts/ufonts.com_american-typewriter-condensed-light.woff') format('woff');
}


@font-face {
font-family: 'American Typewriter Light';
font-style: normal;
font-weight: normal;
src: local('American Typewriter Light'), url('./assets/fonts/ufonts.com_american-typewriter-light.woff') format('woff');
}


@font-face {
font-family: 'American Typewriter Bold';
font-style: normal;
font-weight: normal;
src: local('American Typewriter Bold'), url('./assets/fonts/ufonts.com_american-typewriter-bold.woff') format('woff');
}


@font-face {
font-family: 'American Typewriter Condensed Bold';
font-style: normal;
font-weight: normal;
src: local('American Typewriter Condensed Bold'), url('./assets/fonts/ufonts.com_american-typewriter-condensed-bold.woff') format('woff');
}

body {margin: 1;}



</style> 
